trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

# Debug: show where files actually are
- script: |
    echo "Listing all files in workspace"
    pwd
    ls -R
  displayName: 'List all files recursively'
