trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

# Debug: list files so you can verify paths
- script: ls -R
  displayName: 'List repo files'

# Run abc.py inside Freshers2025 folder
- script: python Freshers2025/abc.py
  displayName: 'Run abc.py'
